import trouble1 from "./images/trouble1.jpg";
import trouble2 from "./images/trouble2.PNG";
import interests1 from "./images/interests1.PNG";
import interests2 from "./images/interests2.jpg";
import interests3 from "./images/interests3.jpg";
import cortina1 from "./images/cortina1.PNG";
import cortina2 from "./images/cortina2.jpg";
import cortina3 from "./images/cortina3.jpg";
import bed from "./images/3Dbed.jpg";
import egg from "./images/egg.PNG";
import lil1 from "./images/lilaugh1.PNG";
import lil2 from "./images/lilaugh2.png";

export const tw1 = trouble1;
export const tw2 = trouble2;
export const in1 = interests1;
export const in2 = interests2;
export const in3 = interests3;
export const cor1 = cortina1;
export const cor2 = cortina2;
export const cor3 = cortina3;
export const bedpic = bed;
export const eggweb = egg;
export const lilpic1 = lil1;
export const lilpic2 = lil2;